#!/usr/bin/env bash
# Time scripting

flag=0
hour=0
min=0
while (($min<61))
do
	if [ $min -eq 0 ]
	then
		echo 'hour:' 0
	elif [ $min -eq 60 ]
	then
		min=$flag
		((hour++))
		echo 'hour:' $hour
		if [ $hour -eq 12 ]
		then
		break
		fi
	else
		echo $min
	fi
	((min++))
done
